### ISSUE TITLE
UX

### ISSUE THREAD

**Issue by Nikita-Zaitsev-ML** [SectumImperial/meta-toxin#1]
в календаре реализовать невозможность выбора даты до текущей

**Comment by Nikita-Zaitsev-ML** [comment]
В Firefox что-то не то со слайдером:
![image](https://user-images.githubusercontent.com/104826556/191975504-e38d0ee2-f2ac-4d77-ad48-c44903cb1441.png)

**Comment by Nikita-Zaitsev-ML** [comment]
pixel perfect нарушен, другие страницы тоже перепроверь

![image](https://user-images.githubusercontent.com/104826556/191976922-7f626ba8-5ab2-41c5-8aa6-b7b1024e9135.png)

**Comment by Nikita-Zaitsev-ML** [comment]
цвета должны совпадать

![image](https://user-images.githubusercontent.com/104826556/191980067-81443fa5-7338-4f48-b262-2ed677eb11f6.png)

**Comment by Nikita-Zaitsev-ML** [comment]
На 1304px выглядит не очень

![image](https://user-images.githubusercontent.com/104826556/191986172-c48bb440-d8e3-4d54-b4f0-cd84d43e4c31.png)

**Comment by Nikita-Zaitsev-ML** [comment]
по макету тут должна быть разделительная полоса

![chrome_89aKeuqsnN](https://user-images.githubusercontent.com/104826556/191987082-2be108e4-d3ca-4079-9881-a8749a507465.png)

**Comment by Nikita-Zaitsev-ML** [comment]
разная толщина 

![image](https://user-images.githubusercontent.com/104826556/191988593-61b71d6c-95a7-466b-a543-5f9c6c86c7e6.png)

**Comment by Nikita-Zaitsev-ML** [comment]
выравнено не по центру(margin забыл убрать, хотя его в целом не должно быть т.к. если это для выравнивания - то нарушается [CSS 2.6](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#2.6))

![image](https://user-images.githubusercontent.com/104826556/191988974-3e69c14b-58ca-42db-9fea-1feb10405649.png)

**Comment by Nikita-Zaitsev-ML** [comment]
использование миксов и неявных зависимостей запрещено: [CSS 4.6](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.6), [CSS 4.4](https://github.com/fullstack-development/front-end-best-practices/blob/master/CSS/README.md#4.4)

Для вспомогательных наборов стилей можно воспользоваться `@mixin` scss

![image](https://user-images.githubusercontent.com/104826556/191989343-53ac6e5f-c5e6-42c2-9a60-31f8e1719d10.png)
![image](https://user-images.githubusercontent.com/104826556/191993163-4f092b64-ac86-442c-bee0-57a0e32f3a18.png)

**Comment by Nikita-Zaitsev-ML** [comment]
не должно быть переноса
![image](https://user-images.githubusercontent.com/104826556/191990901-013bee52-3a85-44f1-b78d-47445bbfeb82.png)

**Comment by Nikita-Zaitsev-ML** [comment]
не происходит пересчет

![image](https://user-images.githubusercontent.com/104826556/192006039-b48ba8c0-aa07-41fa-ba9a-6bf6c0321812.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Это явно должна быть кнопка
нет маски

![image](https://user-images.githubusercontent.com/104826556/192008286-abeabef5-5179-4c40-8be5-0f026583cad0.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Надо поправить эти места, остальное ок:
![image](https://user-images.githubusercontent.com/104826556/195109766-51dd5083-e8f1-4997-a8e2-0fed20280549.png)
![image](https://user-images.githubusercontent.com/104826556/195109881-ba0f87a0-b3fb-4852-910c-c92d78c3d2ff.png)
![image](https://user-images.githubusercontent.com/104826556/195110118-73d158c4-f37f-4992-bc75-de93f7c0661d.png)
![image](https://user-images.githubusercontent.com/104826556/195110506-cfa0cf47-fade-4fc5-85ed-dfdaa15cab01.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Лучше сделать чтобы не съезжало таким образом: кружочек не должен быть на отдельной строке от текста
![image](https://user-images.githubusercontent.com/104826556/195112076-203119d2-2271-44f4-b188-6d9bcaa1b81a.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Обычно это плохая идея уменьшать элементы на мобилке: пальцем неудобно попадать. Часто наоборот делают интерактивные элементы побольше

![image](https://user-images.githubusercontent.com/104826556/195121429-5114e52c-5821-46fc-86fd-183b81a8fde2.png)

**Comment by Nikita-Zaitsev-ML** [comment]
![image](https://user-images.githubusercontent.com/104826556/195122758-ca6a3640-cc26-469d-b250-e0cfed9e62a1.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Подсказки и им подобные вещи лучше делать с `position: fixed` и вставлять в `body`: это избавит от проблем когда элемент с подсказкой надо будет использовать в элементе с `overflow: hidden` или `transition + transform`
![image](https://user-images.githubusercontent.com/104826556/195123253-14e2b9d1-72e1-4fc0-96a6-1645fac687d6.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Я бы сказал что это кнопка type="submit" (не забудь в `form` обернуть)

![image](https://user-images.githubusercontent.com/104826556/195124691-7bf590d5-e3e5-44d1-a713-59a5b7abe168.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Обычно эти места часто меняются(особенно для мультиязычных проектов) и чтобы не было такого смещения лучше сделать ширину фиксированной для колонки, [HTML 1.3](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#1.3)

![image](https://user-images.githubusercontent.com/104826556/195637677-59b8700e-3e64-4ca6-8c51-6647f09c2ebf.png)

**Comment by Nikita-Zaitsev-ML** [comment]
думаю стоит ограничить ширину 
![image](https://user-images.githubusercontent.com/104826556/195638789-03aca1e4-2bb5-4c72-a79c-d9b27b20b1b4.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Стоит учитывать что может быть так, если текст не является статическим(хотя и для них лучше предусматривать подобную ситуацию т.к. часто в админке есть возможность редактировать тексты и для этого не должен требоваться разработчик), [HTML 2.18](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.18)

![image](https://user-images.githubusercontent.com/104826556/195641033-687a9c2d-9897-45ec-8982-26ff28e01aee.png)

**Comment by Nikita-Zaitsev-ML** [comment]
кнопки доступны с клавиатуры, а сам календарь - нет

![image](https://user-images.githubusercontent.com/104826556/195642583-e8051839-22cb-46b0-8708-1d1ebb632308.png)

**Comment by Nikita-Zaitsev-ML** [comment]
toggle не переключается клавиатурой

![image](https://user-images.githubusercontent.com/104826556/195642800-848f13ca-fa21-4ceb-a90e-358495a55ba8.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Выделяется табом и лучше использовать `<output>`
P.S. указанный тэг можно использовать и в других местах

Если сфокусироваться на ползунке, то табуляция перестаёт работать.


![image](https://user-images.githubusercontent.com/104826556/195643353-115dc8db-77db-49e6-b194-63719a42cdd4.png)

**Comment by Nikita-Zaitsev-ML** [comment]
не должно быть такого смещения при клике

![chrome_40MbUBFE0c](https://user-images.githubusercontent.com/104826556/195644088-b5cd2216-3f09-4ab3-b380-85ce0407d334.gif)

**Comment by Nikita-Zaitsev-ML** [comment]
не переключается с клавиатуры

![image](https://user-images.githubusercontent.com/104826556/195644705-d87d4ea0-e0eb-49b1-aea3-72c7505f238c.png)

**Comment by Nikita-Zaitsev-ML** [comment]
не открывается с клавиатуры

![image](https://user-images.githubusercontent.com/104826556/195644813-5f53c4b5-fca5-4bea-8952-a8b95102eea0.png)

**Comment by Nikita-Zaitsev-ML** [comment]
теряется позиция табуляции

![chrome_HFMVKzu2sv](https://user-images.githubusercontent.com/104826556/195645221-99392ea0-9930-4d8d-9b5e-551e84722d56.gif)

**Comment by Nikita-Zaitsev-ML** [comment]
порядок табуляции странный

![chrome_EqXnMLbPSn](https://user-images.githubusercontent.com/104826556/195645484-c7111e4d-c2bc-4d96-9301-16fc78596787.gif)

**Comment by Nikita-Zaitsev-ML** [comment]
картинка перевернута

![chrome_zdUmiZMUuC](https://user-images.githubusercontent.com/104826556/195648433-04778f98-a1b8-44cc-8da7-27c6aa68d745.gif)

**Comment by Nikita-Zaitsev-ML** [comment]
цвета не в том порядке

![chrome_dgVBWSbTyY](https://user-images.githubusercontent.com/104826556/195648635-b91124dd-f2d1-42bf-ac48-21a7e1db3c47.gif)

**Comment by Nikita-Zaitsev-ML** [comment]
цвет разделителя не тот

![chrome_8PzrxOiIwV](https://user-images.githubusercontent.com/104826556/195648875-49d93d77-bcc4-42af-a01f-03abb94baffa.gif)

**Comment by Nikita-Zaitsev-ML** [comment]
нет стрелочки

![chrome_4crwfIa1zs](https://user-images.githubusercontent.com/104826556/195649424-1de5af07-38a1-4be7-8c24-d0e9bd4477bd.gif)

**Comment by Nikita-Zaitsev-ML** [comment]
это `label`, а не `h5`

![image](https://user-images.githubusercontent.com/104826556/195653403-d57a59a8-bebb-4188-8e3c-6642a5c468ee.png)

**Comment by Nikita-Zaitsev-ML** [comment]
это заголовок

![image](https://user-images.githubusercontent.com/104826556/195654256-5791b115-5c67-4e3e-badc-34437149bf35.png)

**Comment by Nikita-Zaitsev-ML** [comment]
лучше явно добавлять атрибут disabled

![chrome_r8md8v0gvK](https://user-images.githubusercontent.com/104826556/195660160-3407f820-3253-401c-b6ce-c1693084c1ac.png)

**Comment by Noeviax** [comment]
> Надо поправить эти места, остальное ок: ![image](https://user-images.githubusercontent.com/104826556/195109766-51dd5083-e8f1-4997-a8e2-0fed20280549.png) ![image](https://user-images.githubusercontent.com/104826556/195109881-ba0f87a0-b3fb-4852-910c-c92d78c3d2ff.png) ![image](https://user-images.githubusercontent.com/104826556/195110118-73d158c4-f37f-4992-bc75-de93f7c0661d.png) ![image](https://user-images.githubusercontent.com/104826556/195110506-cfa0cf47-fade-4fc5-85ed-dfdaa15cab01.png)

У меня PP сходится. 
![image](https://user-images.githubusercontent.com/55241963/196244906-929a7789-8d2d-4e1a-a6cd-df07c310a40d.png)

**Comment by Noeviax** [comment]
> toggle не переключается клавиатурой
> 
> ![image](https://user-images.githubusercontent.com/104826556/195642800-848f13ca-fa21-4ceb-a90e-358495a55ba8.png)

Переключается нажатием на проблем. На enter отправка формы. 
![image](https://user-images.githubusercontent.com/55241963/196245085-444b4815-aba3-4e95-aada-049e0aa608aa.png)

**Comment by Noeviax** [comment]
> ![image](https://user-images.githubusercontent.com/104826556/195122758-ca6a3640-cc26-469d-b250-e0cfed9e62a1.png)

Там скидка в 2к. Так в макете. 
![image](https://user-images.githubusercontent.com/55241963/196245226-fd79ad5c-ce7a-4e21-9ec2-0ec0ae8c77cb.png)

**Comment by Noeviax** [comment]
> не открывается с клавиатуры
> 
> ![image](https://user-images.githubusercontent.com/104826556/195644813-5f53c4b5-fca5-4bea-8952-a8b95102eea0.png)

Открывается на пробел.

**Comment by Nikita-Zaitsev-ML** [comment]
все еще не сходится

![image](https://user-images.githubusercontent.com/104826556/210080446-37d53888-d277-45ce-a30d-9be08bacccc4.png)

**Comment by Nikita-Zaitsev-ML** [comment]
невычислимые свойства следует назначать через специально выделенный селектор-класс

[JS 1.24](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.24)

![image](https://user-images.githubusercontent.com/104826556/210081244-8e7e2f00-2c7c-46d8-82e8-ccd8efc91076.png)

**Comment by Nikita-Zaitsev-ML** [comment]
Нужно добавить обновление позиции при скролле и ресайзе)
Причем ресайз лучше сразу через `ResizeObserver`

![chrome_v6U6l2PaFi](https://user-images.githubusercontent.com/104826556/210081286-c4a14341-f860-4433-b9a9-35848615e93c.gif)

**Comment by Nikita-Zaitsev-ML** [comment]
лучше выровнять аналогично остальным блокам

![image](https://user-images.githubusercontent.com/104826556/210082045-5ce2f803-344a-43b3-ae57-3173278d884d.png)

**Comment by Nikita-Zaitsev-ML** [comment]
`№` лучше отдельно не оставлять
между колонками лучше добавить отступ
карточки должны быть одинаковы по высоте(ограничиваем перенос контента или в сетке прописываем что высота элементов одинаковая)

![image](https://user-images.githubusercontent.com/104826556/210082680-b8a2ec5c-0e37-4433-a484-72e795f84a01.png)

**Comment by Nikita-Zaitsev-ML** [comment]
кнопка "применить" должна быть последней при фокусеровке, [HTML 2.15](https://github.com/fullstack-development/front-end-best-practices/blob/master/HTML/README.md#2.15)
Полезно было бы добавить закрытие по `ESC`

![chrome_mZzxDYVFe1](https://user-images.githubusercontent.com/104826556/210083180-408c814a-1042-4580-a0d7-1bc6f6023dfc.gif)

**Comment by Nikita-Zaitsev-ML** [comment]
Теперь теряется позиция фокуса при клике по кнопке со стрелкой

![chrome_rkpGC3Hwo5](https://user-images.githubusercontent.com/104826556/210083974-6cc7d18d-158d-43e3-a148-e5202b5c279a.gif)

**Comment by Nikita-Zaitsev-ML** [comment]
> невычислимые свойства следует назначать через специально выделенный селектор-класс
> 
> [JS 1.24](https://github.com/fullstack-development/front-end-best-practices/blob/master/JS/README.md#1.24)
> 
> ![image](https://user-images.githubusercontent.com/104826556/210081244-8e7e2f00-2c7c-46d8-82e8-ccd8efc91076.png)

еще осталось

![image](https://user-images.githubusercontent.com/104826556/224316353-57931499-04ea-4069-b476-971691469230.png)

**Comment by Nikita-Zaitsev-ML** [comment]
> `№` лучше отдельно не оставлять между колонками лучше добавить отступ карточки должны быть одинаковы по высоте(ограничиваем перенос контента или в сетке прописываем что высота элементов одинаковая)
> 
> ![image](https://user-images.githubusercontent.com/104826556/210082680-b8a2ec5c-0e37-4433-a484-72e795f84a01.png)

отмечу лишь что для того чтобы избежать переноса более очевидным решением было бы использовать неразрывный пробел `&nbsp;` или `white-space: nowrap`. Можно не исправлять.
